version: "3"
services:
  web:
    build: .
    environment:
      DATABASE_URI: 'sqlite:////docker/storage/storage.db'
    volumes:
      - ./docker:/docker
      - ./magnumopus:/home/user/magnumopus
    ports:
      - 5000:5000
